name: Security Updates

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # Run daily at 3am UTC
  schedule:
    - cron: '0 3 * * *'  # Runs at 3am every day

defaults:
  run:
    shell: bash

jobs:
  security-updates:
    name: Security Updates (Composer Packages)

    runs-on: ubuntu-latest
    container:
      image: devwithlando/php:8.1-apache-4

    env:
      CI: GITHUB_ACTIONS

    steps:
      - name: Configure secure directory
        run: git config --global --add safe.directory "*"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare environment variables
        run: |
          echo "GITHUB_REF_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "COMPOSER_BIN=$(echo ${GITHUB_WORKSPACE}/vendor/bin)" >> $GITHUB_ENV

      # Caching based on existing workflow pattern
      - name: Determine Composer cache directory
        shell: bash
        run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"

      - name: Cache dependencies installed with Composer
        uses: actions/cache@v4
        with:
          path: |
            "${{ env.COMPOSER_CACHE_DIR }}"
            $GITHUB_WORKSPACE/vendor
          key: os-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Check Composer version
        run: composer --version

      - name: Install Composer dependencies
        run: |
          composer validate
          composer self-update
          composer install --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Make script executable
        run: chmod +x ./scripts/custom/security-updates.sh

      - name: Run security check
        run: ./scripts/custom/security-updates.sh

      # If you need to store the artifacts from this job
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: composer-dependencies
          path: |
            vendor/
            composer.json
            composer.lock
