<?php

/**
 * Implements hook_theme().
 */
function dhsc_site_theme() {
  return [
    'social_media_links' => [
      'variables' => [
        'social_links' => [],
      ],
    ],
    'search_form' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'featured_links' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'footer_branding' => [
      'variables' => [
        'logo' => null,
        'variant' => null,
        'site_slogan' => null,
        'site_name' => null
      ],
    ],
  ];
}
