<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_theme().
 */
function dhsc_site_theme() {
  return [
    'social_media_links' => [
      'variables' => [
        'social_links' => [],
      ],
    ],
    'search_form' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'featured_links' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_form_mode_alter().
 */
function dhsc_site_entity_form_mode_alter(&$form_mode, EntityInterface $entity) {

  if (!$entity instanceof ParagraphInterface) {
    return;
  }

  if ($entity->getType() !== 'accordion'
    // @todo switch content type to Skill.
    && $entity->getParentEntity()->getType() !== 'landing_page') {
    return;
  }

  $form_mode = 'skills_framework';
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function dhsc_site_entity_view_mode_alter(&$view_mode, EntityInterface $entity)
{
  if (!$entity instanceof ParagraphInterface) {
    return;
  }

  if ($entity->getType() !== 'accordion'
    // @todo switch content type to Skill.
    && $entity->getParentEntity()->getType() !== 'landing_page') {
    return;
  }

  $view_mode = 'skills_framework';
}
